WARNING 2017-11-15 11:26:42,394 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:26:42,397 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:26:42,399 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:26:42,401 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:26:42,403 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:26:42,405 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:26:42,406 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:26:42,408 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:26:42,410 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:26:42,454 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:26:42,456 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:26:42,487 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:26:42,490 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:26:42,492 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:26:42,503 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:26:42,505 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:26:42,507 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:26:42,509 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:26:42,511 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:26:42,538 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:26:42,673 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:26:42,779 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:26:42,781 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:26:42,783 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:26:42,785 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:26:42,787 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:26:42,789 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:26:42,790 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:26:42,792 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:26:42,794 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:26:42,796 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:26:42,797 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:26:42,800 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:26:42,802 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:26:42,803 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:26:42,805 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:26:42,807 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:26:42,809 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:26:42,811 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:26:42,813 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:26:42,817 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:26:42,821 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:26:42,898 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:26:42,924 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:26:42,925 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:26:42,929 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:26:42,931 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:26:42,933 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:26:42,934 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:26:42,938 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 11:27:12,378 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:27:12,381 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:27:12,382 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:27:12,385 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:27:12,387 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:27:12,389 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:27:12,391 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:27:12,393 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:27:12,395 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:27:12,435 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:27:12,437 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:27:12,467 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:27:12,469 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:27:12,471 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:27:12,482 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:27:12,484 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:27:12,486 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:27:12,488 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:27:12,489 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:27:12,515 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:27:12,674 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:27:12,782 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:27:12,784 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:27:12,786 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:27:12,788 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:27:12,790 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:27:12,792 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:27:12,793 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:27:12,795 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:27:12,797 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:27:12,799 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:27:12,800 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:27:12,802 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:27:12,804 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:27:12,806 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:27:12,808 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:27:12,810 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:27:12,812 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:27:12,813 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:27:12,815 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:27:12,819 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:27:12,823 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:27:12,910 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:27:12,932 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:27:12,934 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:27:12,938 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:27:12,939 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:27:12,941 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:27:12,943 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:27:12,946 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 11:27:42,384 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:27:42,387 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:27:42,388 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:27:42,390 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:27:42,393 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:27:42,394 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:27:42,396 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:27:42,398 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:27:42,400 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:27:42,443 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:27:42,445 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:27:42,479 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:27:42,481 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:27:42,483 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:27:42,495 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:27:42,497 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:27:42,499 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:27:42,500 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:27:42,503 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:27:42,530 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:27:42,667 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:27:42,774 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:27:42,776 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:27:42,777 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:27:42,779 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:27:42,781 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:27:42,783 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:27:42,784 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:27:42,786 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:27:42,788 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:27:42,790 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:27:42,791 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:27:42,793 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:27:42,795 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:27:42,797 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:27:42,799 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:27:42,800 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:27:42,803 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:27:42,805 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:27:42,806 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:27:42,810 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:27:42,814 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:27:42,889 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:27:42,912 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:27:42,914 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:27:42,917 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:27:42,919 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:27:42,921 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:27:42,923 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:27:42,926 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 11:28:12,390 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:28:12,392 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:28:12,394 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:28:12,396 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:28:12,398 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:28:12,400 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:28:12,402 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:28:12,404 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:28:12,406 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:28:12,446 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:28:12,448 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:28:12,482 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:28:12,484 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:28:12,486 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:28:12,500 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:28:12,502 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:28:12,504 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:28:12,506 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:28:12,508 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:28:12,536 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:28:12,684 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:28:12,796 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:28:12,799 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:28:12,800 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:28:12,802 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:28:12,804 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:28:12,806 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:28:12,808 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:28:12,810 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:28:12,812 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:28:12,814 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:28:12,816 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:28:12,818 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:28:12,820 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:28:12,821 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:28:12,823 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:28:12,825 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:28:12,826 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:28:12,829 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:28:12,831 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:28:12,834 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:28:12,837 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:28:12,924 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:28:12,956 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:28:12,958 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:28:12,962 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:28:12,964 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:28:12,966 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:28:12,968 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:28:12,971 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 11:28:42,390 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:28:42,392 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:28:42,394 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:28:42,396 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:28:42,398 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:28:42,400 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:28:42,402 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:28:42,404 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:28:42,406 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:28:42,449 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:28:42,451 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:28:42,486 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:28:42,488 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:28:42,489 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:28:42,500 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:28:42,502 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:28:42,504 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:28:42,507 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:28:42,509 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:28:42,546 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:28:42,683 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:28:42,787 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:28:42,789 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:28:42,791 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:28:42,793 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:28:42,794 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:28:42,796 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:28:42,798 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:28:42,799 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:28:42,801 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:28:42,803 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:28:42,804 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:28:42,806 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:28:42,808 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:28:42,810 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:28:42,811 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:28:42,813 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:28:42,815 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:28:42,817 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:28:42,818 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:28:42,822 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:28:42,826 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:28:42,898 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:28:42,921 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:28:42,923 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:28:42,926 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:28:42,928 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:28:42,930 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:28:42,932 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:28:42,935 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 11:29:12,396 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:29:12,398 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:29:12,400 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:29:12,403 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:29:12,404 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:29:12,406 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:29:12,408 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:29:12,410 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:29:12,412 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:29:12,454 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:29:12,456 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:29:12,488 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:29:12,490 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:29:12,491 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:29:12,502 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:29:12,504 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:29:12,506 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:29:12,508 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:29:12,509 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:29:12,536 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:29:12,696 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:29:12,804 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:29:12,806 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:29:12,808 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:29:12,810 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:29:12,811 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:29:12,813 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:29:12,815 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:29:12,817 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:29:12,818 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:29:12,820 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:29:12,822 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:29:12,824 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:29:12,826 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:29:12,827 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:29:12,829 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:29:12,831 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:29:12,833 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:29:12,835 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:29:12,836 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:29:12,840 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:29:12,843 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:29:12,918 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:29:12,947 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:29:12,949 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:29:12,952 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:29:12,954 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:29:12,955 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:29:12,957 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:29:12,961 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 11:29:42,401 hadoop_util.py[line:183]: this application application_1508997803791_0006 is not a spark type application
WARNING 2017-11-15 11:29:42,403 hadoop_util.py[line:183]: this application application_1508997803791_0005 is not a spark type application
WARNING 2017-11-15 11:29:42,405 hadoop_util.py[line:183]: this application application_1508997803791_0004 is not a spark type application
WARNING 2017-11-15 11:29:42,407 hadoop_util.py[line:183]: this application application_1508997803791_0003 is not a spark type application
WARNING 2017-11-15 11:29:42,409 hadoop_util.py[line:183]: this application application_1508997803791_0002 is not a spark type application
WARNING 2017-11-15 11:29:42,411 hadoop_util.py[line:183]: this application application_1508997803791_0001 is not a spark type application
WARNING 2017-11-15 11:29:42,413 hadoop_util.py[line:183]: this application application_1509434950632_0001 is not a spark type application
WARNING 2017-11-15 11:29:42,415 hadoop_util.py[line:183]: this application application_1509434950632_0002 is not a spark type application
WARNING 2017-11-15 11:29:42,416 hadoop_util.py[line:183]: this application application_1508997803791_0007 is not a spark type application
WARNING 2017-11-15 11:29:42,453 hadoop_util.py[line:183]: this application application_1509085892079_0004 is not a spark type application
WARNING 2017-11-15 11:29:42,455 hadoop_util.py[line:183]: this application application_1509085892079_0003 is not a spark type application
WARNING 2017-11-15 11:29:42,483 hadoop_util.py[line:183]: this application application_1509343490195_0020 is not a spark type application
WARNING 2017-11-15 11:29:42,485 hadoop_util.py[line:183]: this application application_1509343490195_0019 is not a spark type application
WARNING 2017-11-15 11:29:42,487 hadoop_util.py[line:183]: this application application_1509343490195_0021 is not a spark type application
WARNING 2017-11-15 11:29:42,497 hadoop_util.py[line:183]: this application application_1509343490195_0027 is not a spark type application
WARNING 2017-11-15 11:29:42,498 hadoop_util.py[line:183]: this application application_1509436254805_0074 is not a spark type application
WARNING 2017-11-15 11:29:42,500 hadoop_util.py[line:183]: this application application_1509436254805_0071 is not a spark type application
WARNING 2017-11-15 11:29:42,503 hadoop_util.py[line:183]: this application application_1509436254805_0068 is not a spark type application
WARNING 2017-11-15 11:29:42,505 hadoop_util.py[line:183]: this application application_1509436254805_0065 is not a spark type application
WARNING 2017-11-15 11:29:42,534 hadoop_util.py[line:183]: this application application_1509436254805_0062 is not a spark type application
WARNING 2017-11-15 11:29:42,695 hadoop_util.py[line:183]: this application application_1509436254805_0086 is not a spark type application
WARNING 2017-11-15 11:29:42,801 hadoop_util.py[line:183]: this application application_1509436254805_0083 is not a spark type application
WARNING 2017-11-15 11:29:42,803 hadoop_util.py[line:183]: this application application_1509343490195_0014 is not a spark type application
WARNING 2017-11-15 11:29:42,805 hadoop_util.py[line:183]: this application application_1509343490195_0016 is not a spark type application
WARNING 2017-11-15 11:29:42,806 hadoop_util.py[line:183]: this application application_1509436254805_0080 is not a spark type application
WARNING 2017-11-15 11:29:42,808 hadoop_util.py[line:183]: this application application_1509343490195_0015 is not a spark type application
WARNING 2017-11-15 11:29:42,810 hadoop_util.py[line:183]: this application application_1509343490195_0018 is not a spark type application
WARNING 2017-11-15 11:29:42,812 hadoop_util.py[line:183]: this application application_1509343490195_0017 is not a spark type application
WARNING 2017-11-15 11:29:42,813 hadoop_util.py[line:183]: this application application_1509436254805_0077 is not a spark type application
WARNING 2017-11-15 11:29:42,815 hadoop_util.py[line:183]: this application application_1509436254805_0044 is not a spark type application
WARNING 2017-11-15 11:29:42,816 hadoop_util.py[line:183]: this application application_1509436254805_0041 is not a spark type application
WARNING 2017-11-15 11:29:42,818 hadoop_util.py[line:183]: this application application_1509436254805_0038 is not a spark type application
WARNING 2017-11-15 11:29:42,820 hadoop_util.py[line:183]: this application application_1509436254805_0035 is not a spark type application
WARNING 2017-11-15 11:29:42,822 hadoop_util.py[line:183]: this application application_1509436254805_0029 is not a spark type application
WARNING 2017-11-15 11:29:42,824 hadoop_util.py[line:183]: this application application_1509436254805_0059 is not a spark type application
WARNING 2017-11-15 11:29:42,825 hadoop_util.py[line:183]: this application application_1509436254805_0056 is not a spark type application
WARNING 2017-11-15 11:29:42,827 hadoop_util.py[line:183]: this application application_1509436254805_0053 is not a spark type application
WARNING 2017-11-15 11:29:42,829 hadoop_util.py[line:183]: this application application_1509436254805_0050 is not a spark type application
WARNING 2017-11-15 11:29:42,831 hadoop_util.py[line:183]: this application application_1509436254805_0047 is not a spark type application
WARNING 2017-11-15 11:29:42,832 hadoop_util.py[line:183]: this application application_1509436254805_0012 is not a spark type application
WARNING 2017-11-15 11:29:42,836 hadoop_util.py[line:183]: this application application_1509436254805_0008 is not a spark type application
WARNING 2017-11-15 11:29:42,839 hadoop_util.py[line:183]: this application application_1509436254805_0006 is not a spark type application
WARNING 2017-11-15 11:29:42,915 hadoop_util.py[line:183]: this application application_1509436254805_0024 is not a spark type application
WARNING 2017-11-15 11:29:42,942 hadoop_util.py[line:183]: this application application_1509436254805_0022 is not a spark type application
WARNING 2017-11-15 11:29:42,944 hadoop_util.py[line:183]: this application application_1509436254805_0021 is not a spark type application
WARNING 2017-11-15 11:29:42,947 hadoop_util.py[line:183]: this application application_1509436254805_0019 is not a spark type application
WARNING 2017-11-15 11:29:42,950 hadoop_util.py[line:183]: this application application_1509436254805_0018 is not a spark type application
WARNING 2017-11-15 11:29:42,952 hadoop_util.py[line:183]: this application application_1509436254805_0017 is not a spark type application
WARNING 2017-11-15 11:29:42,954 hadoop_util.py[line:183]: this application application_1509436254805_0016 is not a spark type application
WARNING 2017-11-15 11:29:42,957 hadoop_util.py[line:183]: this application application_1509436254805_0014 is not a spark type application
WARNING 2017-11-15 13:37:03,816 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510723824991, 'finishedTimeEnd': 1510725024991}
WARNING 2017-11-15 13:57:04,502 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 14:17:04,083 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 14:37:03,959 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 14:57:03,844 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 15:17:04,018 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 15:37:03,881 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 15:57:03,859 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 16:17:03,906 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 16:37:03,889 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 16:57:03,952 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 17:17:03,877 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 17:37:03,885 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 17:57:03,888 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 18:17:03,891 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 18:37:03,899 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 18:57:03,901 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 19:17:03,906 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 19:37:03,912 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 19:57:03,915 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 20:17:03,919 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
ERROR 2017-11-15 20:39:11,205 hadoop_util.py[line:66]: <urlopen error [Errno 110] Connection timed out>
ERROR 2017-11-15 20:39:11,205 hadoop_util.py[line:96]: <urlopen error [Errno 110] Connection timed out>
WARNING 2017-11-15 20:57:09,331 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 21:17:09,136 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 21:37:09,160 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 21:57:15,352 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
ERROR 2017-11-15 22:19:11,205 hadoop_util.py[line:96]: <urlopen error [Errno 110] Connection timed out>
ERROR 2017-11-15 22:19:11,205 hadoop_util.py[line:66]: <urlopen error [Errno 110] Connection timed out>
WARNING 2017-11-15 22:37:03,952 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 22:57:03,958 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 23:17:04,077 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 23:37:10,999 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-15 23:57:51,617 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 00:17:03,977 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 00:37:03,983 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 00:57:03,983 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 01:17:09,589 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
ERROR 2017-11-16 01:39:11,205 hadoop_util.py[line:96]: <urlopen error [Errno 110] Connection timed out>
ERROR 2017-11-16 01:39:11,205 hadoop_util.py[line:66]: <urlopen error [Errno 110] Connection timed out>
WARNING 2017-11-16 01:57:04,001 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 02:17:04,013 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 02:37:04,008 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 02:57:09,213 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 03:17:09,216 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 03:37:04,022 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 03:57:09,437 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 04:17:04,029 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
ERROR 2017-11-16 04:39:11,333 hadoop_util.py[line:96]: <urlopen error [Errno 110] Connection timed out>
ERROR 2017-11-16 04:39:11,333 hadoop_util.py[line:66]: <urlopen error [Errno 110] Connection timed out>
WARNING 2017-11-16 04:57:51,245 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 05:17:09,290 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 05:37:04,070 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 05:57:15,252 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 06:17:04,059 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 06:37:04,084 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 06:57:09,266 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 07:17:04,081 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 07:37:04,075 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 07:57:04,078 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 08:17:04,105 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 08:37:04,131 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 08:57:04,092 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 09:17:04,098 hadoop_util.py[line:183]: this application application_1509436254805_0135 is not a spark type application
WARNING 2017-11-16 09:27:05,654 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795633353, 'finishedTimeEnd': 1510796233353}
WARNING 2017-11-16 09:29:05,091 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:10,094 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:15,102 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:20,105 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:25,109 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:30,112 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:35,141 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:40,122 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:45,126 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:29:50,133 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795221734, 'finishedTimeEnd': 1510795821734}
WARNING 2017-11-16 09:40:30,165 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510795979884, 'finishedTimeEnd': 1510796579884}
WARNING 2017-11-16 09:43:12,675 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510796653057, 'finishedTimeEnd': 1510797253057}
WARNING 2017-11-16 09:53:12,678 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510796653057, 'finishedTimeEnd': 1510797253057}
WARNING 2017-11-16 10:03:12,686 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 10:13:12,695 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 10:23:13,213 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 10:33:12,701 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 10:43:12,805 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 10:53:12,711 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 11:03:12,712 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 11:13:12,716 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 11:23:12,726 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 11:33:12,770 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 11:43:12,782 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 11:53:12,734 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 12:03:12,773 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 12:13:12,752 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 12:23:13,002 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 12:33:12,752 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 12:43:12,753 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 12:53:12,761 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 13:03:12,762 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 13:13:12,782 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 13:23:12,771 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 13:33:12,778 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 13:43:12,784 hadoop_util.py[line:183]: this application application_1509436254805_0370 is not a spark type application
WARNING 2017-11-16 13:47:43,502 hadoop_util.py[line:160]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510811151126, 'finishedTimeEnd': 1510811751126}
WARNING 2017-11-16 13:48:54,160 hadoop_util.py[line:182]: this application application_1509436254805_0416 is not a spark type application
WARNING 2017-11-16 13:50:28,241 hadoop_util.py[line:161]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510811055544, 'finishedTimeEnd': 1510811655544}
WARNING 2017-11-16 13:51:14,779 hadoop_util.py[line:161]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510811641121, 'finishedTimeEnd': 1510812241121}
WARNING 2017-11-16 13:52:17,793 hadoop_util.py[line:161]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510811715522, 'finishedTimeEnd': 1510812315522}
WARNING 2017-11-16 13:56:16,922 hadoop_util.py[line:161]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510812084763, 'finishedTimeEnd': 1510812684763}
WARNING 2017-11-16 13:56:58,715 hadoop_util.py[line:162]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510811918651, 'finishedTimeEnd': 1510812518651}
WARNING 2017-11-16 13:57:35,306 hadoop_util.py[line:186]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 13:58:37,249 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 14:08:37,254 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 14:18:37,260 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 14:28:37,266 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 14:38:37,270 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 14:48:37,272 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 15:08:37,285 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 15:08:37,286 hadoop_util.py[line:188]: this application application_1509436254805_0417 is not a spark type application
ERROR 2017-11-16 15:18:37,275 hadoop_util.py[line:66]: <urlopen error [Errno 111] Connection refused>
ERROR 2017-11-16 15:18:37,275 hadoop_util.py[line:95]: <urlopen error [Errno 111] Connection refused>
ERROR 2017-11-16 15:28:37,279 hadoop_util.py[line:66]: <urlopen error [Errno 111] Connection refused>
ERROR 2017-11-16 15:28:37,279 hadoop_util.py[line:95]: <urlopen error [Errno 111] Connection refused>
WARNING 2017-11-16 15:39:19,564 hadoop_util.py[line:188]: this application application_1509436254805_0418 is not a spark type application
WARNING 2017-11-16 15:47:05,084 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:48:05,101 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:49:05,102 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:50:05,099 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:51:05,099 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:52:05,123 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:53:05,108 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:54:05,114 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:55:05,118 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:56:05,126 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:57:05,130 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:58:05,135 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 15:59:05,134 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 16:00:05,138 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 16:01:05,144 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 16:02:05,622 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 16:03:05,189 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510818430794, 'finishedTimeEnd': 1510818490794}
WARNING 2017-11-16 16:07:04,976 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:08:05,116 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:09:04,992 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:10:04,991 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:11:04,997 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:12:04,996 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:13:05,514 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:14:05,024 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:15:05,024 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:16:05,014 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:17:09,148 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:22:47,079 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:22:47,080 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:22:48,430 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:24:03,811 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:24:03,858 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:24:03,886 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:24:42,281 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:25:06,928 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:26:09,048 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:27:05,352 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:28:23,105 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:29:05,342 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:30:05,771 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:31:05,232 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:32:05,236 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:33:05,092 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:34:05,099 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:35:05,106 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:36:05,123 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:37:05,120 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:38:05,121 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:39:05,122 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:40:05,144 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:41:05,996 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:42:05,288 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:43:05,138 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:44:05,143 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:45:05,146 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:46:05,151 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:47:05,177 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:48:05,177 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:49:05,198 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:50:05,180 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:51:05,183 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:52:05,192 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:53:09,516 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:54:05,193 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:55:05,194 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:56:05,240 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:57:05,207 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:58:05,389 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 16:59:05,286 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:00:05,255 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:01:05,221 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:02:05,227 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:03:05,234 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:04:05,275 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:05:05,607 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:06:05,243 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:07:05,310 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:08:05,278 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:09:05,258 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:10:05,263 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:11:05,272 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:12:05,295 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:13:05,284 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:14:05,286 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:15:05,331 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:16:05,348 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:17:06,163 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:18:05,306 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:19:05,320 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:20:05,313 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:21:05,322 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:22:05,328 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:23:05,330 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:24:05,337 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:25:05,337 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:26:05,344 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:27:05,351 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:28:05,350 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:29:05,358 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:30:05,360 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:31:05,369 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:32:05,380 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:33:05,379 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:34:05,387 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:35:05,386 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:36:05,390 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:37:05,400 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:38:05,402 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:39:05,406 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:40:05,413 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:41:05,426 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:42:05,418 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:43:05,418 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:44:05,424 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:45:05,427 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:46:05,433 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:47:05,437 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:48:05,446 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:49:05,452 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:50:05,456 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:51:05,459 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:52:05,469 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:53:05,468 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:54:05,473 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:55:05,475 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:56:05,481 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:57:05,486 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:58:05,488 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 17:59:05,495 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:00:05,503 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:01:05,499 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:02:05,510 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:03:05,512 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:04:05,516 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:05:05,519 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:06:05,540 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:07:05,536 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:08:05,546 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:09:05,545 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:10:05,553 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:11:05,552 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:12:05,561 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:13:05,559 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:14:05,562 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:15:05,568 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:16:05,572 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:17:05,589 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:18:05,593 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:19:05,602 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:20:05,602 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:21:05,607 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:22:05,614 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:23:05,616 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:24:05,623 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:25:05,628 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:26:05,636 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:27:05,633 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:28:05,637 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:29:05,643 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:30:05,654 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:31:05,651 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:32:05,661 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:33:05,668 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:34:05,672 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:35:05,671 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:36:05,677 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:37:05,681 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:38:05,701 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:39:05,699 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
WARNING 2017-11-16 18:40:05,695 hadoop_util.py[line:165]: dit not get any data from parameters {'state': 'finished', 'finishedTimeBegin': 1510820521074, 'finishedTimeEnd': 1510820581074}
ERROR 2017-11-16 18:42:05,693 hadoop_util.py[line:95]: <urlopen error [Errno 111] Connection refused>
ERROR 2017-11-16 18:42:05,693 hadoop_util.py[line:66]: <urlopen error [Errno 111] Connection refused>
ERROR 2017-11-16 18:42:08,805 hadoop_util.py[line:95]: <urlopen error [Errno 111] Connection refused>
ERROR 2017-11-16 18:42:08,805 hadoop_util.py[line:66]: <urlopen error [Errno 111] Connection refused>
